[package]
name = "alfred-mic"
version = "0.1.0"
edition = "2021"

[dependencies]
alfred-rs = { path = "../alfred-rs" }
pv_recorder = "*"
hound = "3.5"
anyhow = "1.0.86"
env_logger = "0.11.3"
uuid = { version = "1.8.0", features = ["v4"] }
